// angular/app/components/history.component.ts
import { Component } from '@angular/core';
import { gotoState, redo, undo } from '../../actions';
import stateHistory from '../../statehistory';
import store from '../../store';

@Component({
  selector: 'history',
  template: `
  <input type='range' #range
    style='cursor: pointer'
    min={1} 
    (input)='setState(range.value)'
    [max]='maximum'
    [value]='value'/>

  <a href='#' style='text-decoration: none'
    (click)='previousState()'
    [innerHTML] = 'leftArrow'>
  </a>

  <a href='#' style='text-decoration: none'
    (click)='nextState()'
    [innerHTML] = 'rightArrow'>
  </a>
  `
})

export default class History {  
  private leftArrow: string;
  private rightArrow: string;
  private stateHistory: any;
  private topic: string;
  private unsubscribe: any;
  private value: number;
  private maximum: number;

  constructor() {
    this.stateHistory = stateHistory;

    this.unsubscribe = store.subscribe(() => {
      this.setArrows();

      this.topic = store.getState().topic;
      this.maximum = this.max();
      this.value = this.val();
    });
  }

  setArrows() {
    const last = stateHistory.past.length + stateHistory.future.length;
    const index = stateHistory.getIndex();

    this.leftArrow = index === 0 ? '' : '&larr;';
    this.rightArrow = index === last ? '' : '&rarr;';
  }

  setState(stateIndex) {
    store.dispatch(gotoState(stateIndex));
  }

  previousState() {
    store.dispatch(undo());
  }

  nextState() {
    store.dispatch(redo());
  }
  
  val() {
    return this.stateHistory.past ? this.stateHistory.past.length : 0;
  }

  max() {
    return (this.stateHistory.past    ? this.stateHistory.past.length   : 0) +
           (this.stateHistory.present ? 1 : 0)             +
           (this.stateHistory.future  ? this.stateHistory.future.length : 0) - 1;
  }

  ngOnDestroy() {
    this.unsubscribe();
  }
}

// react/components/history.js
import React from 'react';

export const History = ({
  past, present, future,
  undo, redo, gotoState,
}) => {
  const styles = {
    container: {
      marginLeft: '20px',
      cursor: 'pointer',
    },

    link: { textDecoration: 'none' },
    input: { cursor: 'pointer' },
  };

  const RightArrow = () => (
    <a href="#"
      style={styles.link}
      onClick={() => redo()}
    >
      &#8594;
    </a>
  );

  const LeftArrow = () => (
    <a href="#"
      style={styles.link}
      onClick={() => undo()}
    >
      &#8592;
    </a>
  );

  const max = () => (
    (past    ? past.length   : 0) +
    (present ? 1 : 0)             +
    (future  ? future.length : 0) - 1
  );

  const value = () => past ? past.length : 0;

  return (
    <span style={styles.container}>
      History

      <input type="range"
        style={styles.input}
        min={1} 
        max={max()} 
        value={value()}
        onChange={event => gotoState(event.target.value)} />

      { (past   && past.length   > 0) ? <LeftArrow />  : null }
      { (future && future.length > 0) ? <RightArrow /> : null }
    </span>
  );
};

History.propTypes = {
  past: React.PropTypes.array.isRequired,
  present: React.PropTypes.object.isRequired,
  future: React.PropTypes.array.isRequired,

  undo: React.PropTypes.func.isRequired,
  redo: React.PropTypes.func.isRequired,
  gotoState: React.PropTypes.func.isRequired,
};
