// react/components/stateviewer.js
import React from 'react';

const StateViewer = ({
  topic,
  books,
  currentStatus,
  displayMode,
  history,
}) => {
  const styles = {
    container: {
      margin: '20px',
      width: '400px',
      fontFamily: 'tahoma',
    },

    title: {
      fontSize: '24px',
      marginTop: '25px',
    },

    state: {
      marginTop: '10px',
    },

    hr: {
      marginTop: '50px',
    },
  };

  return (
    <div style={styles.container}>
      <hr style={styles.hr} />

      <div style={styles.title}>
        Application State
      </div>

      <div style={styles.state}>
        Topic: {topic}<br />

        Display mode:      { displayMode }<br />
        Current status:    { currentStatus }<br />
        Books displayed:   { books.length }<br />
        Actions processed: { history.past.length + history.future.length + 1 }<br />
        Current action:    { history.past.length + 1 }
      </div>
    </div>
  );
};

StateViewer.propTypes = {
  books: React.PropTypes.array.isRequired,
  currentStatus: React.PropTypes.string.isRequired,
  displayMode: React.PropTypes.string.isRequired,
  history: React.PropTypes.object.isRequired,
  topic: React.PropTypes.string.isRequired,
};

export default StateViewer;

// angular/app/components/stateviewer.component.ts
import { Component } from '@angular/core';
import store from '../../store';
import stateHistory from '../../statehistory';

@Component({
  selector: 'state-viewer',
  template: `
  <hr/>

  <span style='font-style: tahoma; font-size: 1.5em'>
    Application State
  </span>

  <div style='padding-top: 10px'>
    Topic: {{state.topic}}<br />
    Display mode: {{state.displayMode}}<br />
    Books displayed:   {{ state.books.length }}<br />
    Actions processed: {{ stateHistory.past.length + 
                          stateHistory.future.length + 1 }}<br />
    Current action:    {{ stateHistory.past.length + 1 }}
  </div>
  `
})

export default class StateViewer {  
  private state: any;
  private stateHistory: any;
  private unsubscribe: any;

  constructor(
  ){
    this.state = store.getState();
    this.stateHistory = stateHistory;

    this.unsubscribe = store.subscribe(() => {
      this.state = store.getState();
    });
  }

  ngOnDestroy() {
    this.unsubscribe();
  }
}
